// src/app/landing-zone/particle-canvas/particle-canvas.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-particle-canvas',
  templateUrl: './particle-canvas.component.html',
  styleUrls: ['./particle-canvas.component.scss'],
})
export class ParticleCanvasComponent implements OnInit {
  // particle canvas variables
  particleStyle: object = {};
  particleParams: object = {};
  width: number = 100;
  height: number = 100;

  // initialize settings for the Particle canvas
  ngOnInit() {
    this.particleStyle = {
      display: 'block',
      width: '100%',
      height: '100%',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    };

    this.particleParams = {
      particles: {
        number: {
          value: 110,
          density: {
            enable: true,
            value_area: 800,
          },
        },
        color: {
          value: '#ffffff',
        },
        shape: {
          type: 'polygon',
          stroke: {
            width: 0,
            color: '#000000',
          },
          polygon: {
            nb_sides: 5,
          },
          image: {
            src: 'img/github.svg',
            width: 100,
            height: 100,
          },
        },
        opacity: {
          value: 0.5,
          random: false,
          anim: {
            enable: false,
            speed: 1,
            opacity_min: 0.1,
            sync: false,
          },
        },
        size: {
          value: 3.5,
          random: true,
          anim: {
            enable: false,
            speed: 40,
            size_min: 0.1,
            sync: false,
          },
        },
        line_linked: {
          enable: true,
          distance: 135,
          color: '#44cefc',
          opacity: 0.3,
          width: 1,
        },
        move: {
          enable: true,
          speed: 0.5,
          direction: 'none',
          random: false,
          straight: false,
          out_mode: 'out',
          bounce: false,
          attract: {
            enable: false,
            rotateX: 600,
            rotateY: 1200,
          },
        },
      },
      interactivity: {
        detect_on: 'canvas',
        events: {
          onhover: {
            enable: true,
            mode: 'grab',
          },
          onclick: {
            enable: true,
            mode: 'repulse',
          },
          resize: true,
        },
        modes: {
          grab: {
            distance: 100,
            line_linked: {
              opacity: 0.2,
            },
          },
          bubble: {
            distance: 200,
            size: 40,
            duration: 2,
            opacity: 8,
            speed: 3,
          },
          repulse: {
            distance: 100,
            duration: 1,
          },
          push: {
            particles_nb: 4,
          },
          remove: {
            particles_nb: 10,
          },
        },
      },
      retina_detect: true,
    };
  }

  // // watch scroll location and set styles for the caption
  // @HostListener('window:scroll', [])
  // onScroll(): void {
  //   // document.documentElement.setAttribute('data-scroll', window.scrollY.toString());

  //   let pos =
  //     (document.documentElement.scrollTop || document.body.scrollTop) +
  //     document.documentElement.offsetHeight;
  //   let max = document.documentElement.scrollHeight;
  //   // pos/max will give you the distance between scroll bottom and and bottom of screen in percentage.
  //   if (pos >= (max*.95)) {
  //     document.documentElement.dataset.scrolledBottom = 'true';
  //     // document.documentElement.setAttribute('data-scrolled-bottom', 'true');
  //   } else {
  //     document.documentElement.dataset.scrolledBottom = 'false';
  //     // document.documentElement.setAttribute('data-scrolled-bottom', 'false');
  //   }
  //   //   this.nameStyle = {};
  //   //   this.subtitleStyle = {};
  //   //   this.buttonStyle = {
  //   //     ...this.buttonStyle,
  //   //     'justify-content': 'right',
  //   //   };
  //   //   this.scrollDownVisible = 'hidden';
  //   // } else {
  //   //   this.nameStyle = {
  //   //     margin: '0 0 .5em 0',
  //   //   };
  //   //   this.subtitleStyle = {
  //   //     margin: '0 0 1em 0',
  //   //     height: '100%',
  //   //   };
  //   //   this.buttonStyle = {
  //   //     ...this.buttonStyle,
  //   //     'justify-content': 'left',
  //   //   };
  //   //   this.scrollDownVisible = 'visible';
  // }
}

<section class="particle-canvas">
  <particles
    [style]="particleStyle"
    [params]="particleParams"
    [width]="width"
    [height]="height"
  ></particles>
  <app-caption></app-caption>
  <app-scroll-down></app-scroll-down>
</section>

// components/ParticleCanvas.tsx
import { useCallback } from 'react'
import Particles from 'react-tsparticles'
import { loadFull } from 'tsparticles'
import { Container, Engine } from 'tsparticles-engine'

const ParticleCanvas = (): JSX.Element => {
  const particlesInit = useCallback(async (engine: Engine) => {
    console.log(engine)

    // you can initialize the tsParticles instance (engine) here, adding custom shapes or presets
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    await loadFull(engine)
  }, [])

  const particlesLoaded = useCallback(async (container: Container | undefined) => {
    console.log(container)
  }, [])
  return (
    <Particles
      id='tsparticles'
      init={particlesInit}
      loaded={particlesLoaded}
      options={{
        particles: {
          number: {
            value: 15,
            density: {
              enable: true,
              value_area: 500
            }
          },
          color: {
            value: '#1b1e34'
          },
          shape: {
            type: 'polygon',
            stroke: {
              width: 2,
              color: '#000'
            },
            polygon: {
              sides: 4
            }
          },
          opacity: {
            value: 0.3,
            random: true,
            anim: {
              enable: true,
              speed: 0.05,
              opacity_min: 0,
              sync: false
            }
          },
          size: {
            value: 20,
            random: true,
            anim: {
              enable: true,
              speed: 3,
              size_min: 40,
              sync: false
            }
          },
          lineLinked: {
            enable: false,
            distance: 200,
            color: '#ffffff',
            opacity: 1,
            width: 2
          },
          move: {
            enable: true,
            speed: 0.3,
            direction: 'bottom-right',
            random: false,
            straight: true,
            outMode: 'out',
            bounce: false,
            attract: {
              enable: false,
              rotateX: 0,
              rotateY: 0
            }
          }
        },
        interactivity: {
          detects_on: 'canvas',
          events: {
            onhover: {
              enable: false,
              mode: 'grab'
            },
            onclick: {
              enable: false,
              mode: 'push'
            },
            resize: true
          },
          modes: {
            grab: {
              distance: 400,
              lineLinked: {
                opacity: 1
              }
            },
            bubble: {
              distance: 400,
              size: 40,
              duration: 2,
              opacity: 8,
              speed: 3
            },
            repulse: {
              distance: 200,
              duration: 0.4
            },
            push: {
              particles: 4
            },
            remove: {
              particles: 2
            }
          }
        },
        detectRetina: true
      }}
    />
  )
}

export default ParticleCanvas
